version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8000:80"
    networks:
      - internal
    volumes:
      - ./threel-backend/:/var/www/threel-backend/
      - ./logs/nginx:/var/log/nginx/
    container_name: nginx
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./threel-backend/:/var/www/threel-backend/
      - ./logs/php.log:/var/log/fpm-php.www.log
    depends_on:
      - mysql
    container_name: php
    expose:
      - "9000"
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    # platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'threelAdmin'
      MYSQL_PASS: 'root'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
  mailhog:
    image: mailhog/mailhog
    tty: true
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: on-failure
    networks:
      - internal
networks:
  internal:
    driver: bridge


  # frontend:
  #   build:
  #     context: .
  #     dockerfile: threel-frontend/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - internal
  #   depends_on:
  #     - php
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   container_name: frontend