version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8000:80"
    networks:
      - internal
    volumes:
      - ./threel-backend/:/var/www/threel-backend/
      - ./logs/nginx:/var/log/nginx/
    container_name: nginx
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./threel-backend/:/var/www/threel-backend/
      - ./logs/php.log:/var/log/fpm-php.www.log
    depends_on:
      - mysql
    container_name: php
    expose:
      - "9000"
  react:
    build:
      context: .
      dockerfile: ./threel-frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./threel-frontend:/app
      - /app/node_modules
    networks:
      - internal
    container_name: frontend
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    # platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'threelAdmin'
      MYSQL_PASS: 'root'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
  mailhog:
    image: mailhog/mailhog
    tty: true
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: on-failure
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: 'root'
      PMA_PASSWORD: 'root'
    ports:
      - "8080:80"
    networks:
      - internal
    container_name: phpmyadmin
networks:
  internal:
    driver: bridge